[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.82.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/podcast/adam-jacob-chef/"
  to = "https://enterpriseready.io/podcast/01-adam-jacob-chef/"
  status = 301
  force = true